version: 0.2

phases:
  build:
    commands:
      - aws cloudformation package --s3-bucket awscontroller --template-file template.yaml --output-template-file restapi-output-template.yaml

artifacts:
  type: zip
  files:
    - restapi-output-template.yaml